import  './style.css'
// import './topics/01-tipos-basicos.ts'
// import './ejercicios/di32.ts'
// import './topics/02-objetos-interfaces.ts'
// import './ejercicios/di33.ts'
// import './topics/03-funciones.ts'
// import './ejercicios/di34.ts'
// import './ejercicios/04-tarea-tipos.ts'
// import './topics/05-desestructuracion.ts'
// import './ejercicios/di36.ts'
// import './ejercicios/di37.ts'
// import './ejercicios/ejercicio9.2.ts'
// import './topics/08- clases.ts'
// import './ejercicios/ejercicio3-10.ts'
// import './ejercicios/ejercicio3-11.ts'
import './ejercicios/ejercicio3-12.ts'


